# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CVE JSON Schema
description: > # this means to ignore newlines until "baseurl:"
  cve-schema specifies the CVE JSON record format. 
  This is the blueprint for a rich set of JSON data that can be submitted by CVE Numbering Authorities (CNAs) 
  and Authorized Data Publishers (ADPs) to describe a CVE record. 
  Some examples of CVE record data include CVE ID number, affected product(s), affected version(s), 
  and public references. While those specific items are required when assigning a CVE, 
  there are many other optional data in the schema that can be used to enrich CVE records 
  for community benefit.
show_downloads: false,
theme: jekyll-theme-cayman
markdown: kramdown
